#!/usr/bin/env ruby
# frozen_string_literal: true

require 'toptranslation_cli'
require 'thor'

class Tt < Thor
  package_name :tt

  desc :check, 'Check current configuration'
  def check
    ToptranslationCli::Check.run
  end

  desc :help, 'Print usage information'
  def help(*args, **kwargs)
    return super(*args, **kwargs) if !args.empty? || !kwargs.empty?

    version

    # We need to call super without arguments
    super()

    puts <<~URLS
      twitter:
        @tt_developers (https://twitter.com/tt_developers)

      websites:
        https://www.toptranslation.com
        https://developer.toptranslation.com
        https://github.com/Toptranslation/tt_cli
    URLS
  end

  desc :init, "Create an example configuration file #{ToptranslationCli::Configuration::FILENAME}"
  def init
    ToptranslationCli::Initializer.run
  end

  desc :push, 'Upload local documents'
  def push
    ToptranslationCli::Push.run
  end

  desc :pull, 'Download remote translations, overwriting local documents'
  def pull
    ToptranslationCli::Pull.run
  end

  desc :version, 'Print version'
  def version
    puts "Toptranslation command line client, version #{ToptranslationCli::VERSION}"
    puts ''
  end
end

Tt.start(ARGV)
